/*
 * Copyright 2026 Centerscout GmbH
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.mtanalyze.export;

import com.mtanalyze.profile.DataHelper;
import com.mtanalyze.profile.DataHelper.CompCell;
import com.mtanalyze.util.FileChoosers;
import com.prowidesoftware.swift.model.SwiftTagListBlock;

import org.apache.poi.common.usermodel.HyperlinkType;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellStyle;
import org.apache.poi.ss.usermodel.CreationHelper;
import org.apache.poi.ss.usermodel.Font;
import org.apache.poi.ss.usermodel.Hyperlink;
import org.apache.poi.ss.usermodel.IndexedColors;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.function.Consumer;

/** Writes MT entries as a pivoted .xlsx workbook with components split into columns. */
public final class ExcelExport {

    private static final int    MAX_AUTOSIZE_COLS = 200;
    private static final String BRAND_TEXT        = "Generated by MT Analyze (www.mtanalyze.com)";
    private static final String BRAND_URL         = "https://www.mtanalyze.com";
    private static final DateTimeFormatter TIMESTAMP_FORMAT =
            DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");

    private final DataHelper dataHelper = new DataHelper();

    public void exportComponents(JFrame owner, List<SwiftTagListBlock> seqs,
                                  List<Map<String, String>> rowData, String seqKey,
                                  Consumer<String> status) {
        if (seqs.isEmpty()) {
            JOptionPane.showMessageDialog(owner, "Please load a SWIFT file first.",
                    "No Data", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        File file = pickFile(owner);
        if (file == null) return;
        try {
            List<CompCell> compCells = dataHelper.collectAllComponentCells(seqs, rowData, seqKey);
            writeWorkbook(file, compCells);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(owner, "Error during export:\n" + ex.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        status.accept("Exported: " + file.getAbsolutePath());
        CsvExport.offerOpenFile(owner, file);
    }

    private static File pickFile(JFrame owner) {
        JFileChooser fc = FileChoosers.create();
        fc.setDialogTitle("Save Excel File");
        fc.setFileFilter(new FileNameExtensionFilter("Excel Workbook (*.xlsx)", "xlsx"));
        fc.setSelectedFile(new File("SWIFT_Components.xlsx"));
        if (fc.showSaveDialog(owner) != JFileChooser.APPROVE_OPTION) return null;
        File file = fc.getSelectedFile();
        if (!file.getName().toLowerCase(Locale.ROOT).endsWith(".xlsx"))
            file = new File(file.getAbsolutePath() + ".xlsx");
        return file;
    }

    private static void writeWorkbook(File file, List<CompCell> cells) throws IOException {
        LinkedHashMap<String, String>  colHeaders = new LinkedHashMap<>();
        LinkedHashMap<String, Integer> colIndex   = new LinkedHashMap<>();
        LinkedHashMap<String, Integer> entryIndex = new LinkedHashMap<>();

        for (CompCell c : cells) {
            String ck = c.seqLabel() + "\t" + c.tagName() + "\t" + c.qualifier() + "\t" + c.label();
            colIndex.computeIfAbsent(ck, key -> {
                colHeaders.put(key, compColHeader(c.seqLabel(), c.tagName(), c.qualifier(), c.label()));
                return colIndex.size();
            });
            entryIndex.putIfAbsent(c.entry(), entryIndex.size());
        }

        Object[][] data = new Object[entryIndex.size()][colIndex.size()];
        for (CompCell c : cells) {
            String ck = c.seqLabel() + "\t" + c.tagName() + "\t" + c.qualifier() + "\t" + c.label();
            data[entryIndex.get(c.entry())][colIndex.get(ck)] = c.value();
        }

        try (Workbook wb = new XSSFWorkbook();
             FileOutputStream out = new FileOutputStream(file)) {
            Sheet sheet = wb.createSheet("Components");
            sheet.createFreezePane(0, 1);

            CellStyle headerStyle = wb.createCellStyle();
            Font bold = wb.createFont();
            bold.setBold(true);
            headerStyle.setFont(bold);

            String[] headers = colHeaders.values().toArray(new String[0]);
            Row header = sheet.createRow(0);
            for (int c = 0; c < headers.length; c++) {
                Cell cell = header.createCell(c);
                cell.setCellValue(headers[c]);
                cell.setCellStyle(headerStyle);
            }
            for (int r = 0; r < data.length; r++) {
                Row row = sheet.createRow(r + 1);
                for (int c = 0; c < data[r].length; c++) {
                    Object value = data[r][c];
                    if (value == null) continue;
                    Cell cell = row.createCell(c);
                    if (value instanceof Number n) cell.setCellValue(n.doubleValue());
                    else                            cell.setCellValue(value.toString());
                }
            }
            int autoSizeCount = Math.min(headers.length, MAX_AUTOSIZE_COLS);
            for (int c = 0; c < autoSizeCount; c++) sheet.autoSizeColumn(c);

            addBranding(wb, sheet, data.length); // after auto-size so the long link doesn't widen column 0
            wb.write(out);
        }
    }

    /** Adds a discreet "Generated by MT Analyze" footer: a clickable brand row and an
     *  export timestamp below the data, plus a print-page footer and the document author. */
    private static void addBranding(Workbook wb, Sheet sheet, int dataRows) {
        CreationHelper helper = wb.getCreationHelper();
        String timestamp = LocalDateTime.now(ZoneId.systemDefault()).format(TIMESTAMP_FORMAT);

        Font linkFont = wb.createFont();
        linkFont.setItalic(true);
        linkFont.setUnderline(Font.U_SINGLE);
        linkFont.setColor(IndexedColors.GREY_50_PERCENT.getIndex());
        CellStyle linkStyle = wb.createCellStyle();
        linkStyle.setFont(linkFont);

        Font noteFont = wb.createFont();
        noteFont.setItalic(true);
        noteFont.setColor(IndexedColors.GREY_50_PERCENT.getIndex());
        CellStyle noteStyle = wb.createCellStyle();
        noteStyle.setFont(noteFont);

        Row brandRow = sheet.createRow(dataRows + 2); // header at 0, data 1..dataRows, one blank gap row
        Cell brandCell = brandRow.createCell(0);
        brandCell.setCellValue(BRAND_TEXT);
        brandCell.setCellStyle(linkStyle);
        Hyperlink link = helper.createHyperlink(HyperlinkType.URL);
        link.setAddress(BRAND_URL);
        brandCell.setHyperlink(link);

        Row tsRow = sheet.createRow(dataRows + 3);
        Cell tsCell = tsRow.createCell(0);
        tsCell.setCellValue("Exported " + timestamp);
        tsCell.setCellStyle(noteStyle);

        sheet.getFooter().setLeft("Exported " + timestamp);
        sheet.getFooter().setRight(BRAND_TEXT);

        if (wb instanceof XSSFWorkbook xssf) {
            xssf.getProperties().getCoreProperties().setCreator("MT Analyze");
        }
    }

    private static String compColHeader(String seq, String tag, String qualifier, String comp) {
        StringBuilder sb = new StringBuilder(seq).append(" / ").append(tag);
        if (!qualifier.isEmpty()) sb.append(" / ").append(qualifier);
        return sb.append(" / ").append(comp).toString();
    }
}